### ISSUE TITLE
Increase MSRV to allow for Zeroize > 1.4

### ISSUE THREAD

**Issue by hariria** [dalek-cryptography/curve25519-dalek#388]
Hi, is there any chance we can increase the minimum supported rust version and zeroize to > 1.4? It conflicts with a lot of other crates. Thanks!

Based on what i'm seeing here: https://github.com/Devolutions/picky-rs/issues/140#issuecomment-1093662134

**Comment by samuelvanderwaal** [comment]
I, too, am curious about this.

**Comment by rcolomina** [comment]
What is the problem? Why are setting <1.4 restriction on Zeroize?

**Comment by k0nserv** [comment]
We are hitting this in the webrtc-dtls crate too. We have both `elliptic-curve` and `curve25519-dalek` in our tree. elliptic-curve@v0.12.3 requires `zeroize > 1.5` and `curve25519-dalek` requires `zeroize < 1.4`

**Comment by robjtede** [comment]
Hitting a similar issue to @k0nserv at work with the aws-sdk crates which require zeroize ^1.4.

It's very common in the Cargo ecosystem for MSRV bumps to exist in minor versions. If users of the crate wish to remain on an outdated compiler, they are able to solve MSRV problems themselves by pinning deps (even deep ones) in their own application's manifest.

**Comment by juliotpaez** [comment]
Same problem here with aws-sdk crates and ethereum web3 crates

**Comment by brson** [comment]
Just linking to the issue that established this pinned version: https://github.com/dalek-cryptography/curve25519-dalek/issues/362

**Comment by rozbb** [comment]
This is now resolved in the `release/4.0` branch. Next release (or prerelease) will have a laxer zeroize dependency.

**Comment by k0nserv** [comment]
@rozbb When can we expect a release here? I think for many folks this problem remains unresolved until a release is made(pointing to GitHub will not work well in libraries I think)

**Comment by tarcieri** [comment]
@k0nserv see open items under https://github.com/dalek-cryptography/curve25519-dalek/issues/416
